### PR TITLE
Match changes in Maps 7.2

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Includes bump of PHP version since Maps 7.2 requires 7.1, so
not bumping it helps no one.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
I have not tested this since right now I don't have the time to install this

**Comment by kghbln** [comment]
@JeroenDeDauw Currently I have no time to do a field test so I rather leave this to the code review of @mwjames to move forward here. 

Note, Composer now upgraded to 7.1.0 instead of 7.2.0.  I have no clue which other extension is now getting in the way.

**Comment by JeroenDeDauw** [comment]
> PHP Fatal error:  Declaration of MediaWikiPHPUnitCommand::createRunner() must be compatible with PHPUnit\TextUI\Command::createRunner(): PHPUnit\TextUI\TestRunner in /home/travis/build/SemanticMediaWiki/mw/tests/phpunit/MediaWikiPHPUnitCommand.php on line 3

**Comment by JeroenDeDauw** [comment]
> Note, Composer now upgraded to 7.1.0 instead of 7.2.0. I have no clue which other extension is now getting in the way.

That is caused by the GitHub extension. I will update it.

**Comment by kghbln** [comment]
> That is caused by the GitHub extension. I will update it. You can already install Maps ~7.1 though :)

Cool. Once this is fixed the wiki will automatically pull in the new versions. As for this extension I guess there is something in the pipeline. Once fluffed, give me a ping for me to add it to the "composer.local.json" file.

**Comment by JeroenDeDauw** [comment]
To clarify: I am not planning on poking more at this extension. The changes I provided might fix compat with maps fully, and if not, provide a good starting point.

**Pull request closed without merging**
