### PR TITLE
Inject ParserOutput

### PR DESCRIPTION
**Pull request by mwjames**
https://github.com/JeroenDeDauw/Maps/issues/413

I'd appreciate if we could avoid BC in a minor relase!

### CODE REVIEW

**Comment by kghbln** [comment]
Also fixes https://github.com/SemanticMediaWiki/WhatsNearby/issues/15

**Comment by kghbln** [comment]
@mwjames This change also drops support for PHP 5.4 and earlier or does this only stop testing for it?

**Comment by mwjames** [comment]
> @mwjames This change also drops support for PHP 5.4 and earlier or does this only stop testing for it?

REL1_27 started to complain and I had no intention to investigate why, so I took the high road and used a combination that works. The change itself doesn't change or limit the functionality on PHP 5.4.

**Comment by kghbln** [comment]
Thanks for the info!

**Comment by JeroenDeDauw** [comment]
@mwjames I am considering the Maps code to not be stable from an extension PoV. Maybe in the future it can have a real public API... Until then the code API can contain breaking changes in minor versions, as I am just holding userland features into account for the versions.

**Comment by JeroenDeDauw** [comment]
Then again not that likely this extension will break. And at least now it is in my mind this thing exists and binds to some Maps code

**Comment by mwjames** [comment]
> @mwjames I am considering the Maps code to not be stable from an extension PoV. Maybe in the future it can have a real public API... Until then the code API can contain breaking changes

[0] notes "Software using Semantic Versioning MUST declare a public API. This API could be declared in the code itself or exist strictly in documentation. However it is done, it should be precise and comprehensive."

Well, and here we have a different interpretation of what `semver` means for a project. My interpretation is that unless something is declared as `@private` (class or method) any `public` available interface (class or method) that is accessible is seen as an API that any consumer can rely on when the software is released under semver.

I do see your point and for this particular issue it took only 30 min to fix it but your argument "...  not be stable from an extension PoV. Maybe in the future it can have a real public API ..." in my eyes refutes the idea of what semver is trying to accomplish.

Let's not start a bikeshed on what semver should or is not, I have seen your argument and I presented mine and that should close the topic.

[0] https://semver.org/

**Pull request merged**
