### PR TITLE
Make WhatsNearby work with Maps 6.x and 7.x

### PR DESCRIPTION
**Pull request by kghbln**
@mwjames I assume that this extension also works with Maps 6.x and 7.x

@JeroenDeDauw FYI

### CODE REVIEW

**Comment by mwjames** [comment]
> I assume that this extension also works with Maps 6.x and 7.x

Let's assume this. I haven't changed anything and assuming the interfaces remained as they were, it should work.

**Comment by JeroenDeDauw** [comment]
Won't work with latest Maps. For instance this static function no longer exists https://github.com/SemanticMediaWiki/WhatsNearby/blob/master/src/NearbyParserFunction.php#L125

> assuming the interfaces remained as they were

Most of the Maps PHP code has been rewritten since 5.x. Nearly all of it is clean and shiny now. Might need to add some extension points back in again though.

**Comment by JeroenDeDauw** [comment]
I had a quick look at some stuff (including JS) and the linked static function usage is the only break I saw.

Though there also is the bit where Maps no longer supports OpenLayers.

**Comment by kghbln** [comment]
> I had a quick look at some stuff (including JS) and the linked static function usage is the only break I saw.

So this line should just be removed?

**Comment by JeroenDeDauw** [comment]
As far as I can tell, that linked code in this extension is poking Maps so it loads some javascript that it needs. If that is no longer done, then I expect this extension to break.

**Comment by JeroenDeDauw** [comment]
I'll have a look at this. @kghbln I suggest you just disable whatsnearby on SMW server till this is resolved

**Comment by JeroenDeDauw** [comment]
https://github.com/SemanticMediaWiki/WhatsNearby/pull/22

**Pull request closed without merging**
